version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql
    ports:
      - '${DB_PORT}:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - db

  bull-board:
    image: deadly0/bull-board
    container_name: bull-board
    depends_on:
      - redis
    ports:
      - "${BULL_BOARD_PORT}:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}