version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - redis
    volumes:
      - ./:/app
    networks:
      - backend-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend-net

  bull-board:
    image: deadly0/bull-board
    container_name: bull-board
    depends_on:
      - redis
    ports:
      - "${BULL_BOARD_PORT}:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - backend-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/data/prometheus:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - backend-net

  grafanaT:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
        - ./docker/data/grafana:/var/lib/grafana
        - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - backend-net

  redis-exporter:
    image: oliver006/redis_exporter
    depends_on:
      - redis
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
volumes:
  grafana-data:
  prometheus-data: